### ISSUE TITLE
[FIX] History API go to next or previous page events not updating view

### ISSUE THREAD

**Issue by QuintenJustus** [Protoqol/Prequel#10]
When going to the previous or next page, the view won't update, but the URL does. There should be something  like an event that dispatches and updates the currently selected database (in the view) based on the URL query parameters.

Possible solutions
- Set a hook for the next and previous page events and update based on that URL

**Note: when you're taking up this issue please leave a comment below to let the other users know!**

**Comment by djaxho** [comment]
I can take a look at this issue tonight, if I fail, I'll report back :)

**Comment by djaxho** [comment]
I actually won't have time to take a look until tonight or tomorrow, so if anyone wants to have at it before then, feel free 🙂

**Comment by QuintenJustus** [comment]
@djaxho Take your time! It's not a very pressing at the moment :+1:

**Comment by QuintenJustus** [comment]
Will be merged and included in next release, see #42.
