### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RyonMB** [Protoqol/Prequel#104]
**Describe the bug**
When I try to edit something in the table editor, it does not save

**To Reproduce**
1. Go to any table
2. Edit any field 
3. Refresh
4. Old value is set

**Expected behavior**
Value is edited

**PHP Version**
 - Version 7.4

**Database type**
 - Type mysql

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by QuintenJustus** [comment]
Hi @RyonMB, thanks for bringing up the issue! Unfortunately that feature still needs some tweaks before going live, I am aware that it's a pretty essential feature to have, so this has a high priority. Version 1.3 will certainly have it.
