### ISSUE TITLE
Returns 404 even after enabled in production [BUG]

### ISSUE THREAD

**Issue by just1and0** [Protoqol/Prequel#105]
**Describe the bug**
returns 404 in production, even while enabled.

**To Reproduce**
the set environment in .env file and change;

PREQUEL_ENABLED=true
APP_ENV=production
APP_DEBUG=false

**Expected behavior**
expect to load the expected Prequel URL, but end up seeing 404 pages.

**Comment by QuintenJustus** [comment]
Hi @just1and0, this is not a bug, this is expected behaviour. Prequel will, by default, always be disabled in production. You can, if you’re sure about your case, bypass it by replacing the default middleware.

**Comment by just1and0** [comment]
Thank @QuintenJustus for clarifying.

I have done as advised and created my own middleware.
