### ISSUE TITLE
[BUG] Demo displays an 404 error

### ISSUE THREAD

**Issue by winfried-van-loon** [Protoqol/Prequel#106]
**Describe the bug**
The demo listed in the readme goes to a website which displays an error (404 not found).

**To Reproduce**
1. Go to the readme of the GitHub project
2. Click on the `TL;DR? Test Prequel here!` link
3. The website `https://prequel.protoqol.xyz/prequel` opens

**Expected behavior**
I would have expected to see the demo of Prequel on the website.

**Screenshots**
> <img width="324" alt="Screenshot 2020-07-08 at 15 06 23" src="https://user-images.githubusercontent.com/756956/86922242-9cb43900-c12c-11ea-8636-cc0d2b97e7a4.png">
>
> _The link in the readme file._
---
> <img width="757" alt="Screenshot 2020-07-08 at 15 05 49" src="https://user-images.githubusercontent.com/756956/86922167-8908d280-c12c-11ea-8da4-d002561802ae.png">
> 
> _The website when visited._

**PHP Version**
 - Unknown and not relevant which PHP version the website is running, however it seems to be served by Apache2:
```bash
➜ curl -I https://prequel.protoqol.xyz/prequel
HTTP/2 404
date: Wed, 08 Jul 2020 13:08:09 GMT
server: Apache/2
content-type: text/html; charset=iso-8859-1
```

**Database type**
 - Unknown and not relevant

**Desktop (please complete the following information):**
 - Browser: Google Chrome
 - Version 83.0.4103.116 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
- I haven't tested this on a smartphone.

**Additional context**
Line to the code: https://github.com/Protoqol/Prequel/blob/master/.github/README.md#L30

**Comment by AthosBenther** [comment]
If you try to access the the link without the "/prequel" the following message is displayed

"This account has been suspended.
Either the domain has been overused, or the reseller ran out of resources."

**Comment by QuintenJustus** [comment]
Oops... Didn’t pay on time, thanks for noticing! Will be fixed ASAP

**Comment by QuintenJustus** [comment]
@AthosBenther fixed, you can now view it in action again!
