### ISSUE TITLE
[FEATURE] Implement dark mode

### ISSUE THREAD

**Issue by QuintenJustus** [Protoqol/Prequel#11]
Implement a dark mode, create a button in the top-right that can be switched on and off like the other 2 buttons.

**Comment by James-N-M** [comment]
I’ve been wanting to learn how to do this, I’ll pick this issue up if it’s still up for grabs 💯

**Comment by QuintenJustus** [comment]
Nobody else has taken it, so you’re good to go! Good luck👍

**Comment by QuintenJustus** [comment]
@James-N-M how is dark mode doing? :smile:

**Comment by James-N-M** [comment]
I just finally got it set up to work on last night so hopefully i have a better status update on it tonight or tomorrow. Figuring out the symlinking process from the local git repo package to my test project was a long one, I watched 2 of the three videos on laracasts last night about adding custom themes using tailwind.

**Comment by QuintenJustus** [comment]
Ah alright, nice! There's no hurry, just wanted to check in :smile:.
If you've got any screenshots or something tonight that would be dope! Looking forward to it.

**Comment by James-N-M** [comment]
Ya for sure ! I'll comment them in here hopefully all goes well I dont hit any hiccups with tailwind

**Comment by QuintenJustus** [comment]
If you have any questions you can just drop them here!

**Comment by James-N-M** [comment]
![image](https://user-images.githubusercontent.com/6562688/60934753-6f247d80-a295-11e9-923d-43a884a239bc.png)
finally getting rolling with it.

**Comment by QuintenJustus** [comment]
Looking good! Keep up the great work :smile:

**Comment by James-N-M** [comment]
![image](https://user-images.githubusercontent.com/6562688/60939703-abaca500-a2a6-11e9-8038-b4679e2195d9.png)
I feel like im at a good place with css variables to implement the actual theme switcher functionality maybe tomorrow night or the next day. Well have to have a call or a conversation about what colors we actually want to use for each piece.   A friend recommended i actually take a picture and use a eye dropper to copy my own php storm themes colors 
![image](https://user-images.githubusercontent.com/6562688/60939784-faf2d580-a2a6-11e9-9714-9c601df6d2f2.png)

**Comment by QuintenJustus** [comment]
Nice work, your friend’s recommendation is certainly good one! There’s a discord server for Protoqol where we can discuss, you can find the link int the Dev branch’s README.md at the top.

**Comment by QuintenJustus** [comment]
Implemented in 0c4c3982425dcaa772b5283c65dfd8ff1ac1835c, closing now. New suggestions can be done via a new issue.
