### ISSUE TITLE
How can i put Prequel behind Laravel authentication?

### ISSUE THREAD

**Issue by sarderiftekhar** [Protoqol/Prequel#110]
Hi,

Now the prequel is open to browse for anyone, how can I put it behind login and only for the application admin to view? Is there any feature like that?

**Comment by MCKLtech** [comment]
Late to the party here but you can add a Middleware then place it in the 'middleware' option the config file (prequel.php)

If you wanted all authenticated users to have access to Prequel (Which is not good for production as I assume everyone can log in) then it would look something like this:

`'middleware' => [
            'web',
            'auth'
        ],`

What you really should do is look at packages that provide Roles and then only permit someone to view Prequel if they have that role

**Comment by NicoPli** [comment]
This does not seem to work for me. I use Laravel breeze and when I add 'auth' into the config nothing changes. I can still access Prequel without login in. When I add other changes to the config it works. I reset the cache. I also tried to add Auth::check() to the middleware class of Prequel, but somehow it always returned false. Am I doing something wrong here?
