### ISSUE TITLE
46.js not found

### ISSUE THREAD

**Issue by webstack9** [Protoqol/Prequel#114]
First I would like to say Great Job, I like this package a Lot

**Describe the bug**
missing 46.js file , strange name as well !?

**To Reproduce**
1. Go to Manage'
2. Click on Run Sql
3. Scroll down to  Chrome Console
4. See error "http://localhost:8085/46.js net::ERR_ABORTED 404 (Not Found)"

**PHP Version**
 - Version [8]

**Database type**
 - Type [mysql]
 - Version [8]

**Desktop (popOs):**
 - Browser [chrome]

**Comment by QuintenJustus** [comment]
This is due to an unsuccesfull expirment with SQL code highlighting. This has been removed.
