### ISSUE TITLE
[BUG] Wrong SSL Cert for https://prequel.protoqol.xyz

### ISSUE THREAD

**Issue by bitbayio** [Protoqol/Prequel#147]
**Describe the bug**
Prequel version check at  Prequel/resources/assets/js/components/Elements/Version.vue fails because https://prequel.protoqol.xyz/api/prequel-version uses SSL certificate for '*.zxcs.nl, zxcs.nl' !

**Comment by QuintenJustus** [comment]
@bitbayio thank you for taking the time to make an issue. This has now been fixed in [this release](https://github.com/Protoqol/Prequel/releases/tag/v1.22.61).
