### ISSUE TITLE
Mysql socket connection

### ISSUE THREAD

**Issue by mcmc4519** [Protoqol/Prequel#148]
Hi! Your application is awesome!

**Is your feature request related to a problem? Please describe.**
I have a connection to mysql by socket. When I try use prequel, I have an error: **Could not create a valid database connection**.
In .env file I set a path to DB_SOCKET file.

`DB_SOCKET=/var/lib/mysqld/mysqld.sock`

Can we make a connection by socket?

**Comment by QuintenJustus** [comment]
This is resolved now that #149 has been merged.
