### ISSUE TITLE
[BUG] Look for table ... returns all tables from all databases

### ISSUE THREAD

**Issue by michaelnguyen547** [Protoqol/Prequel#15]
**Describe the bug**
Look for Table... search field should restrict to tables of selected Database

**To Reproduce**
1. Select a database
2. search table name in the search field

**Expected behavior**
Should only display tables belong to the selected database

**Screenshots**
<img width="363" alt="Screen Shot 2019-07-08 at 12 07 20 PM" src="https://user-images.githubusercontent.com/436950/60832416-119b0e80-a179-11e9-9608-0a7de4a4a784.png">

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 75.0.3770.100 

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by QuintenJustus** [comment]
That’s not a bug. That’s supposed to happen, it’s a feature to search for any table in any database.

**Comment by michaelnguyen547** [comment]
I see, thanks
