### ISSUE TITLE
[BUG] The Link : TL;DR? Test Prequel here! Doesn't work

### ISSUE THREAD

**Issue by KazeroG** [Protoqol/Prequel#150]
**Describe the bug**
On the readme file the link [TL;DR? Test Prequel here!](https://prequel.protoqol.xyz/prequel) redirect to (https://protoqol.nlprequel/)

**To Reproduce**
 click the [TL;DR? Test Prequel here!](https://prequel.protoqol.xyz/prequel)

1. Go to readme file
2. Click on [TL;DR? Test Prequel here!](https://prequel.protoqol.xyz/prequel)
3. See error

**Expected behavior**
the link should redirect to the demo of the repo

**PHP Version**

- Version : `live`
- 
**Database type**

- Type : `live`
- Version : `live`

**Desktop (please complete the following information):**

- Browser: `chrome`
- Version: `latest`

**Comment by QuintenJustus** [comment]
Thank you for opening an issue for this! The link has been removed for now.
