### ISSUE TITLE
[BUG] Cannot run raw query

### ISSUE THREAD

**Issue by JordanDalton** [Protoqol/Prequel#151]
**Describe the bug**
Unable to use raw sql feature.

**To Reproduce**

1. From Browse click on the database then a table.
2. Click on 'Manage' on top top navbar.
3. Click "Run SQL"
4. You'll see a section, in a gray box, titled "SQL Query. Write and run a raw SQL query"
5. You'll notice you can't click that section.
6. If you click "Run SQL" you'll observe the following error in the console log:
```
app.js:1 GET https://protoqol.nl/api/prequel-version 404
(anonymous) @ app.js:1
t.exports @ app.js:1
t.exports @ app.js:1
u.request @ app.js:1
r.forEach.u.<computed> @ app.js:1
(anonymous) @ app.js:1
checkVersion @ app.js:1
mounted @ app.js:1
Ft @ app.js:1
tn @ app.js:1
insert @ app.js:1
S @ app.js:1
(anonymous) @ app.js:1
t._update @ app.js:1
r @ app.js:1
pn.get @ app.js:1
pn @ app.js:1
(anonymous) @ app.js:1
kn.$mount @ app.js:1
kn.$mount @ app.js:1
t._init @ app.js:1
kn @ app.js:1
(anonymous) @ app.js:1
n @ app.js:1
(anonymous) @ app.js:1
n @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
app.js:1 TypeError: Cannot set properties of undefined (setting 'style')
    at i.runSql (app.js:1:434859)
    at click (app.js:1:435754)
    at Ft (app.js:1:171521)
    at HTMLButtonElement.n (app.js:1:173263)
    at HTMLButtonElement.Xr.a._wrapper (app.js:1:208873)
```

**Expected behavior**
That you can actually write a custom, raw sql query

**Screenshots**
<img width="1391" alt="Screen Shot 2022-02-01 at 3 02 20 AM" src="https://user-images.githubusercontent.com/1389886/151940054-83fc9ab1-561d-4c2f-8a65-5e51ab58794d.png">

**PHP Version**

- Version 7.3.27

**Database type**

- Type MariaDB
- Version 10.4.13

**Desktop (please complete the following information):**

- Browser Chrome
- Version 97.0.4692.99

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JordanDalton** [comment]
See https://github.com/Protoqol/Prequel/blob/master/resources/assets/js/components/MainContent/ManageMode/ManageActions/RunSQL.vue#L5-L10

**Comment by QuintenJustus** [comment]
This is disabled for now.
