### ISSUE TITLE
[FEATURE REQUEST] Install only in dev env

### ISSUE THREAD

**Issue by wrtisans** [Protoqol/Prequel#16]
**Is your feature request related to a problem? Please describe.**

it would be great install it only on dev environent, if its possible now and im missing someting please let me know

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by QuintenJustus** [comment]
Hey, I’m not really sure what you mean? Could you fill in the other fields aswell, and be more clear on what exactly you’d like to see? Thanks 😁

**Comment by aaronsaray** [comment]
I think what @wrtisans is saying is that they'd only like this installed in dev environment.  In the `Authorised` middleware, there is a check to make sure that the functionality is not enabled in production.  But, regardless, the service provider and other checks are still executed. I think the request has to do with not auto-registering the service provider and following the example in [barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) where user registers it by hand.  One could argue that not registering the service provider is a micro-optimization, and for ease of use, just allow it to continue registering automatically.  Others might say they don't want non-production things even _installed_ on production.

@wrtisans you can get your required desire, I think, by following the above example and adding this package to your `dont-discover` section of your `composer.json` file.

**Comment by wrtisans** [comment]
@aaronsaray great! thats what i was looking!!!
