### ISSUE TITLE
[FEATURE REQUEST] Add support for Laravel 10 #159

### ISSUE THREAD

**Issue by adamczykpiotr** [Protoqol/Prequel#160]
This package is currently missing support for Laravel 10 which came out like a month ago.  I've made a PR #159 to solve this problem.

Until PR is merged, you can use my fork by changing entry in the "require" section of composer.json to `"protoqol/prequel" : "dev-master"` and adding "respositories" section:
```  
  "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/adamczykpiotr/Prequel.git"
        }
    ],

**Comment by QuintenJustus** [comment]
Your pull request was just merged.
