### ISSUE TITLE
[BUG] I can't make icons appears on prequel 2.0

### ISSUE THREAD

**Issue by dnl4** [Protoqol/Prequel#162]
**Describe the bug**
I was using prequel 1.23. Today I updated to prequel 2.0. But I can't manage icons to appear on the web interface.

**To Reproduce**

1. `sail composer require protoqol/prequel:dev-master#e9f5ec1`
2. `sail php artisan prequel:update`
3. access `http://localhost/prequel`

**Expected behavior**
Icons appear on web interface

**Screenshots**
![](https://i.imgur.com/KfGo4oS.png)

**PHP Version**
-PHP 8.1.17

**Database type**
- mysql

**Desktop (please complete the following information):**
- Safari and chrome

**Comment by QuintenJustus** [comment]
Hi @dnl4, thanks for reporting this issue. Did you run `php artisan prequel:install`? Prequel 2.0 is still a WIP so some parts are may not be bootstrapping correctly.
