### ISSUE TITLE
[BUG] Prequel not loading

### ISSUE THREAD

**Issue by dima2306** [Protoqol/Prequel#19]
**Describe the bug**
Installed on Laravel 5.7.28 followed the instructions and got an error in the console. See the screenshot.
As examined main.blade
`<script>
  // Pass initial data to JavaScript
  window.Prequel       = {};
  window.Prequel.env   = @json($env);
  window.Prequel.error = {
    error   : false,
    detailed: '',
    code    : '',
  };
  window.Prequel.data  = @json($data['collection']);
  window.Prequel.flat  = @json($data['flatTableCollection']);
</script>`
problem occurs here: window.Prequel.data  = @ json($data['collection']); (I've specially pressed space at json because github was mentioning related user)

**Screenshots**
![prequel error](https://user-images.githubusercontent.com/16943788/60838366-94ed4c00-a1db-11e9-9941-30d44ddb87c1.png)

**Comment by QuintenJustus** [comment]
Hey thanks for opening the issue here and being concise! Looks like the json passed from the backend is invalid (first error). Could you share some more information about the database you’re using and any other relevant details? Thanks in advance 👍

**Comment by dima2306** [comment]
Hi! I'll wrap up as more information as I can. I can't share all my databases, because some are my job's. But I'll try to find out which database(s) cause this problem.

**Comment by dima2306** [comment]
I've found what was causing the problem. It was one table's name "users_ოლდი" (I'm Georgian user)) ) and the problem occurred in prettifyName of DatabaseTraverser class. Seem like regex is unable to handle Georgian words and was giving unreadable characters. 
![error](https://user-images.githubusercontent.com/16943788/60885797-7c277980-a261-11e9-8fe8-785b7e240836.png)

Once I renamed it in English only words, prequel loaded successfully without any errors.
But it'll be good to handle special characters words also.

**Comment by QuintenJustus** [comment]
Thanks for figuring that out! That’s a pretty major issue so that will probably be patched in the next release! Closing issue now 👍

**Comment by QuintenJustus** [comment]
Hey @dima2306, quick question. What table collation were you using for `users_ოლდი`?

**Comment by dima2306** [comment]
Hi there,
it's utf8_unicode_ci
