### ISSUE TITLE
[BUG] top of page formatting

### ISSUE THREAD

**Issue by toast777** [Protoqol/Prequel#20]
On first page load at /prequel , the top area formatting breaks down and has overlapping UI components if user name is too long.

**Expected behavior**
Clean non-overlapping interface. 

For azure I have to user a username like this - 
username@myserver.mysql.database.azure.com

For security people may user super long usernames as well.

Probably just a CSS fix or something

Chrome version Version 75.0.3770.100 (Official Build) (64-bit) Windows 10 64 bit

**Comment by QuintenJustus** [comment]
Hey, thank you for notifying me! Will take a look at this! Thanks 👍

**Comment by QuintenJustus** [comment]
Fixed and will be merged in next release.

**Comment by toast777** [comment]
Cool thanks, no worries if you don't know, do you know of someone with
experience with MySQL ssl and laravel?

**Comment by QuintenJustus** [comment]
Can't think of anyone I can easily connect you with atm, sorry.
