### ISSUE TITLE
[BUG] Incorrect DB credentials gives cryptic error

### ISSUE THREAD

**Issue by aaronsaray** [Protoqol/Prequel#23]
**Describe the bug**
Purposely, I set the password to my database connection to an incorrect value.  Then I get an error of `Oops... No valid database connection` with a suggestion of `You're using an irregular port number, usually the port is 3306 (Yours is: NaN)`

Couple things wrong here:
* because of the invalid connection, the code is zero'ing out all my config - I think it shouldn't set all the values to null
* because of above, the JSON turns my port number to null (even though it's actually set right)  Even so, it shouldn't say NaN - it should be filtered to parse the integer properly or display a better message

**To Reproduce**
1. modify `.env` `DB_PASSWORD` value to be wrong.

**Expected behavior**
I think it could tell me what the error message was, and then also not null out my values.  I'd like to see them because maybe I have a typo.

**Additional context**
Why would this happen you ask?  Well, right now, it'd be very unlikely.  But, you're publishing DB credential configuration in `config/prequel.php` - which means you most likely want us to use them, too.  My `.env` file could be right, so my application works, but this configuration file (when implemented) might have a typo in it.

Because this is such a particularly weird issue to have, I'd rate it as pretty low priority.

**Comment by QuintenJustus** [comment]
Hey, I could not replicate your issue. I having an invalid password (and username, database etc.) but it just shows me that Prequel could not find a valid connection. Something I'm missing here?

**Comment by QuintenJustus** [comment]
I think this was fixed in f1ab336!

**Comment by QuintenJustus** [comment]
Confirmed to be fixed, so closing now.
