### ISSUE TITLE
[BUG] published config file db credentials don't seem to be used

### ISSUE THREAD

**Issue by aaronsaray** [Protoqol/Prequel#24]
**Describe the bug**
I altered my credentials in the `config/prequel.php` file and they don't seem to affect the existing connection.

**To Reproduce**
1. modify `config/prequel.php` DB.PASSWORD field to something like `aaron-is-causing-trouble` and you should no longer be able to connect. You do, though.

**Expected behavior**
If these exist here, I should be able to change my configuration. I like them because I might want to give Prequel a read-only user - different than my main application, so I'd say try to fix it, not get rid of them. Just my opinion.

**Additional context**
Pretty low priority again.

**Comment by QuintenJustus** [comment]
Currently Prequel uses the default DB instance. A separate dedicated DB instance will be used in the next release to also allow for a separate RO user like you say.

**Comment by QuintenJustus** [comment]
Closing now as this has been noted and will be fixed in next release.
