### ISSUE TITLE
[FEATURE REQUEST] Add pagination default to the config file

### ISSUE THREAD

**Issue by aaronsaray** [Protoqol/Prequel#25]
**Is your feature request related to a problem? Please describe.**
There's no problem. But, some people might not want 100 to be the default pagination from the API.  I think we can put that value in the config file.

**Describe the solution you'd like**
1. Make a config option for default pagination value
2. Set it to 100
3. Modify the controllers to use that.

**Comment by QuintenJustus** [comment]
PR #26 approved for merge in next release! Thanks 👍
