### ISSUE TITLE
[BUG] Invalid database connections

### ISSUE THREAD

**Issue by SerafimArts** [Protoqol/Prequel#29]
Here: 
https://github.com/Protoqol/Prequel/blob/695852c8eb475127f9f2d05945874ddf1b1ed940/src/Http/Controllers/PrequelController.php#L26-L32

In the settings may not exist connections named "`mysql`".

You should take the connection names from the `config/prequel.php` settings.

**Comment by QuintenJustus** [comment]
Nice catch, this is fixed in the next release, do closing now. Thanks for notifying me!

**Comment by SerafimArts** [comment]
Ideally it would be nice to have support for multiple connections.

**Comment by QuintenJustus** [comment]
That's on the to-do list!
