### ISSUE TITLE
[FIX] Tables with same name in different databases

### ISSUE THREAD

**Issue by QuintenJustus** [Protoqol/Prequel#35]
When selecting a table, in a database underneath another database, that has a table with the same name, the first table is marked as active (meaning it gets a different text-color etc.). Meaning if the wrong database.table is marked as active.

Possible solutions
- Better check to see which table is actually active. Like matching database names with table parent element. 

**Note: when you're taking up this issue please leave a comment below to let the other users know!**

**Comment by James-N-M** [comment]
I'll take this issue up @QuintenJustus 💯

**Comment by James-N-M** [comment]
Thanks for assigning me I plan on starting this tomorrow morning

**Comment by James-N-M** [comment]
I'm confused about what the issue actually is, it seems the functionality to highlight the active table name is gone. So does the error occur even if they are one or more databases away from each other

**Comment by QuintenJustus** [comment]
Closing now, see #61 for more information.
