### ISSUE TITLE
[BUG] Users table fields are not showing all data

### ISSUE THREAD

**Issue by M4ST3RX** [Protoqol/Prequel#37]
**Describe the bug**
In a database called "Main" the "Users" table missing two fields therefore the column isn't showing the right data but on any other table or database it is working see in the screenshots.

**To Reproduce**
I have not tried to reproduce the issue as this has been like this since first time opening the table. I guess it is something to do with the naming as I have seen 

**Expected behavior**
Expected to see two more null fields.

**Screenshots**
On phpMyAdmin
![Screenshot 2019-07-11 at 13 54 29](https://user-images.githubusercontent.com/40009052/61056445-47dfc480-a3eb-11e9-9d30-52a1d906ae8d.png)

On Prequel
![Screenshot 2019-07-11 at 13 35 39](https://user-images.githubusercontent.com/40009052/61056434-43b3a700-a3eb-11e9-87a3-e31c3ab5af46.png)

**Desktop (please complete the following information):**
 - Browser: chrome
 - Version: 74

**Comment by QuintenJustus** [comment]
Weird bug! Will look at this tonight, will be fixed in next release.

**Comment by QuintenJustus** [comment]
I think I found out what was causing this, will be fixed in next release.

**Comment by QuintenJustus** [comment]
Closing now as this is probably fixed, if the issue persists in the next release please make a new issue.
