### ISSUE TITLE
[FEATURE REQUEST] Ability to see table structure even with empty tables

### ISSUE THREAD

**Issue by spriggsey** [Protoqol/Prequel#38]
**Is your feature request related to a problem? Please describe.**
When creating new tables/migrations on a brand new project, its nice to be able to check if those table columns are in the correct place, correct collation, length etc, without having to push dummy data right away into it.

**Describe the solution you'd like**
At a minimum it would be great to have the table column structure still showing for empty tables.
A better implementation could also be a different view similar to phpMyAdmin's 'Structure' tab.

**Describe alternatives you've considered**
Filling the table with dummy data solves the issue slightly but It could be nicer to have a more detailed view instead of having to check out the migrations for that table.

**Comment by QuintenJustus** [comment]
Good suggestion. Should be relatively easy, so will probably be there in next release. Thanks for your request!

**Comment by QuintenJustus** [comment]
Implemented in e7e56f3 closing now.
