### ISSUE TITLE
[FEATURE REQUEST] Tests for source code

### ISSUE THREAD

**Issue by aaronsaray** [Protoqol/Prequel#43]
**Is your feature request related to a problem? Please describe.**
It is best practice to include some sort of unit, integration or feature type tests with your libraries.  I tend not to use an open source product / library if they don't have adequate tests.  Not only does it help with code quality and reducing bugs, it gives the reader an idea of how the product functions without having to do a deep-dive into the code.

**Describe the solution you'd like**
I'd like to see some unit tests for both front and back-end code. I'm not proposing anything insane like even 80% code, but some framework to get contributors started.

**Additional context**
It'd be nice to know if this is something that the author doesn't think is important, thinks they didn't have time to do, thinks isn't important, or doesn't know how to implement effectively.  Sharing this sentiment can help contributors understand how to best proceed and help the project.

**Comment by xuanquynh** [comment]
:+1:  Well, I think tests are required for all nice software.

**Comment by QuintenJustus** [comment]
Thanks for your feature request! I'm implementing tests in the new release. Why not earlier? Because I ran into some trouble on my previous attempt, I was using Orchestra's testbench and that didn't go down so well. I'm trying different methods at the moment to get a good overall test coverage, mainly back-end focused for now, but front-end tests are certainly something worth investing in as it's quite a front-end heavy package. If any of you have more experience in Laravel package testing than me, then help is certainly appreciated!

**Comment by xuanquynh** [comment]
Tests are necessary but not required immediately. We can add each one case by case before the pre-released versions. I don't have much experience on Laravel package testing as specially integration testing with Orchestra's testbench. But if you have any trouble, just create issues and the community (including me) can help much more easier.

**Comment by aaronsaray** [comment]
Would you like me to create a branch with orchestra testbench and a few other tests set up for people to build off of?

**Comment by QuintenJustus** [comment]
If you’re willing to, I’d be very grateful 😁👌

**Comment by aaronsaray** [comment]
I did so.  I didn't do all the testing I could have, but I gave some examples.  I would recommend writing more tests as you do the development.  For example, with tests, I was able to figure out that the name of the database configuration was being targeted for a database type, not the driver value itself.  I didn't notice that when I first used the package :)

**Comment by QuintenJustus** [comment]
Nice job! Those tests are enough to build upon further 👍 Also saw your comments about the http statuses being 200, thanks for letting me know!

**Comment by QuintenJustus** [comment]
Merged, see #45. Closing now
