### ISSUE TITLE
[BUG] Path Causes Loading Issue

### ISSUE THREAD

**Issue by jacobshenning** [Protoqol/Prequel#49]
**Describe the bug**
Changing the path in the prequel config file will cause an error when trying to load the data.

**To Reproduce**
1. Follow the prequel install directions on a fresh Laravel app
2. Make sure you have a database connected and prequel works normally
3. Go into the prequel config file and change the path to something like `apps/prequel`
4. Try to load databases at custom URL.
5. See error

**Expected behavior**
I expected prequel to be able to load databases at a custom URL

**Screenshots**
![Screen Shot 2019-07-17 at 11 44 18 AM](https://user-images.githubusercontent.com/15023234/61402564-41889700-a888-11e9-90f1-2dd05e5e617a.png)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 70.0.3538.67 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: N/A
 - Browser N/A
 - Version N/A

**Additional context**
N/A

**Comment by QuintenJustus** [comment]
That’s odd! Will check this tonight!

**Comment by QuintenJustus** [comment]
Should be fixed now, let me know if you have any other suggestions!
