### ISSUE TITLE
[FIX] Clearer horizontal table scrolling

### ISSUE THREAD

**Issue by Protoqol** [Protoqol/Prequel#5]
Currently it is not clear that you can scroll horizontally in the currently selected table. 

Solutions might be
1. Scroll bar at top instead of bottom
2. Fade out on right side to indicate that there is more content
3. Arrow pointing right with same purpose as 2.

**Comment by James-N-M** [comment]
Sounds like a good first issue I'll pick this one up if that's ok

**Comment by Protoqol** [comment]
Sounds good, good luck! If you have any questions you can just drop them here 😁

**Comment by James-N-M** [comment]
I gave it a go but I'm having some trouble setting up and working on the project. I forked the repo and tried to link to the local git repo from one of my laravel projects, and then made a simple change to the Welcome vue component. But the change isnt showing up. So basically my question is whats your process for setting up the project to develop it locally. Or do you have a tutorial link or documentation.

**Comment by Protoqol** [comment]
Hey, I have yet to make a proper contribution guide + testing resources. So here’s a shortened version. If the following is not working or is too much of a hassle, then wait a little bit until I get contribution all setup.

0. Create laravel project or use existing one, as long as it has a database connection.
1. Inside the project run `composer require protoqol/prequel’ and navigate to `vendors/protoqol/prequel`
2. Run `npm install`
3. (if making changes to php) Run `composer install`
4. Take a look at the package.json, you’ll that there are a bunch of laravel mix commands.
5. It’s best to use `npm run watch`, this creates a local server with hot-reloading.

Thanks for taking up the issue! I’m sorry for the lack of documentation and resources, I totally forgot while opening the issue! So if you’re still willing to take it, good luck! And else, no hard feelings!

**Comment by QuintenJustus** [comment]
Fixed by @James-N-M in #7
