### ISSUE TITLE
[FEATURE REQUEST] Customizable Authorization

### ISSUE THREAD

**Issue by cashlion** [Protoqol/Prequel#51]
**Is your feature request related to a problem? Please describe.**
Access to the dashboard is currently bound by an environment variable. 

**Describe the solution you'd like**
Similar to Nova, Horizon, etc, I’d like to be able to enable access in production but restrict access based on different criteria like a user role, user email, IP address, etc.

**Comment by QuintenJustus** [comment]
Hey Cashlion, thanks for your feature request! I just pushed a new feature (see 27cfafd67e345e640a5dde75c174add23d4d6981), is this what you're looking for?

**Comment by QuintenJustus** [comment]
Closing now as there has been no answer and the feature mentioned above is probably the fix for this.
