### ISSUE TITLE
[BUG] Fields are not shown when using the $visible property

### ISSUE THREAD

**Issue by stevenberg** [Protoqol/Prequel#52]
**Describe the bug**
When a model class uses the `$visible` property to hide attributes, attributes that are not included in the `$visible` array are not shown in Prequel.

**To Reproduce**
Use the `$visible` property instead of `$hidden`:

```php
protected $visible = [
    'created_at',
    'email',
    'id',
    'name',
    'updated_at',
];
```

**Screenshots**
Expected view:
![Screen Shot 2019-07-18 at 9 54 59 AM](https://user-images.githubusercontent.com/2222/61464799-e23c8c80-a944-11e9-82e4-12b1425b12e1.png)

Actual view:
![Screen Shot 2019-07-18 at 9 52 48 AM](https://user-images.githubusercontent.com/2222/61464819-ea94c780-a944-11e9-9767-d440d6c43552.png)

**Fix**
I think this can be fixed by changing line 76 of DatabaseController.php from

```php
$paginated->setCollection($paginated->getCollection()->makeVisible($hidden));
```

to

```php
$paginated->getCollection()->each->setHidden([])->each->setVisible([]);
```

Which removes both the `$hidden` and `$visible` properties from the objects in the collection.

**Comment by QuintenJustus** [comment]
Thanks for including a fix! Included in next release.
