### ISSUE TITLE
[BUG] Routing

### ISSUE THREAD

**Issue by M4ST3RX** [Protoqol/Prequel#54]
**Describe the bug**
The current api url is /prequel-api but status still querying the /prequel/prequel-api/status url.

**To Reproduce**
1. Go to '/prequel'
2. Open DevTools
3. See status requests failing

**Expected behavior**
Seeing status query the right url so it can get the information from the database.

**Screenshots**
![image](https://user-images.githubusercontent.com/40009052/61572797-2b065980-aa9b-11e9-9cbb-318b5e22e881.png)

**Desktop (please complete the following information):**
 - Browser Google Chrome
 - Version 75

**Additional context**
This may be just for me as I have made some changes and now updated to latest version but not changed the routes file.
If it occurs for others too then change `->prefix('/prequel-api')` to `->prefix(config('prequel.path') . '/prequel-api')` or the js that makes the query.

**Comment by M4ST3RX** [comment]
Also migration still sends request to `/prequel-api/run/migrations` but the route have been changed to `/prequel-api/migrations/run`

**Comment by QuintenJustus** [comment]
Run `$ php artisan prequel:update` 👌 There’s been some changes to the routes file.

**Comment by M4ST3RX** [comment]
Ah yeah the changes made some conflicts and broke the js/css but it is now fixed.
