### ISSUE TITLE
[FEATURE REQUEST] php artisan prequel:remove

### ISSUE THREAD

**Issue by dykow** [Protoqol/Prequel#62]
I would really like to see a easy way to remove Prequel. Just the opposite command to `php artisan prequel:install`

**Comment by QuintenJustus** [comment]
Might be something we'll add in the future, for now follow the instructions below.

#### In your project root folder: 
```bash
$ rm -r ./public/protoqol/prequel
$ rm -r ./resources/lang/vendor/prequel
$ composer remove protoqol/prequel
```

**Comment by dykow** [comment]
> Might be something we'll add in the future, for now follow the instructions below.
> #### In your project root folder:
> 
> ```shell
> $ rm -r ./public/protoqol/prequel
> $ rm -r ./resources/lang/vendor/prequel
> $ composer remove protoqol/prequel
> ```

Sadly none of these paths exists, I can see only `/public/vendor/prequel`. No signs of prequel in `resources` directory.

**Comment by QuintenJustus** [comment]
Nevermind the resources/lang! That's only in the Dev branch, sorry 😄
