### ISSUE TITLE
How to contribute [Question]

### ISSUE THREAD

**Issue by jacobshenning** [Protoqol/Prequel#66]
Hey @QuintenJustus, I want to contribute to this repository. I build apps with Vue and Laravel often. I also have a lot of cool ideas for this app.

Before I get carried away though, I just want to try making some basic contributions. Do you have any "good first issues" for me?

**Comment by QuintenJustus** [comment]
Hey! Absolutely, if you could pop me an email we can discuss it there! 😁👌
