### ISSUE TITLE
Don't infer database type from name and support multiple connections

### ISSUE THREAD

**Issue by gjm** [Protoqol/Prequel#67]
AFAIK Prequel is inferring the database type from the connection name (`mysql`, `pgsql`, etc.). I can only specify one database connection, also.

In my case I have more than one database connection, all using the same driver (`pgsql`) but with different names. As such, when I try to access Prequel I get an error saying my database is not supported.

I would like to be able to use Prequel to manage all my connections. Am I missing something (namely some config option) that allows me to do so?

**Comment by jacobshenning** [comment]
@gjm Prequel 1.13 currently only supports one database connection. Multiple database connections is likely to come in the future, but has not been planned in any upcoming releases yet.

**Comment by QuintenJustus** [comment]
Closing as Jacob’s response answered correctly.
