### ISSUE TITLE
[BUG] There was an error while loading this table

### ISSUE THREAD

**Issue by berandakreatif** [Protoqol/Prequel#68]
**Describe the bug**
I tried to use your package, until displaying the database listing was running normally, when I clicked one of the tables from the database an error statement appeared

There was an error while loading this table. See the following:
Could not resolve error 
Prequel suggests looking at the following points
Prequel could not suggest any fixes

**Screenshots**
![gambar](https://user-images.githubusercontent.com/32983386/62340794-fc609800-b50a-11e9-876d-9d35b78d53b9.png)

**Desktop (please complete the following information):**
 - Browser : Mozila Firefox

**Smartphone (please complete the following information):**
 - Device: Laptop

**Comment by HDVinnie** [comment]
Is it only that table that throws this error? If so please share the DB schema for this table.

**Comment by HDVinnie** [comment]
@berandakreatif any update?

**Comment by QuintenJustus** [comment]
Thanks @HDVinnie. Closing now since there was no response.
