### ISSUE TITLE
[FEATURE REQUEST] Any roadmap or plan for when the "Manage" screen will be ready?

### ISSUE THREAD

**Issue by robtesch** [Protoqol/Prequel#74]
Hi there guys, firstly thank you for this fantastic package. All is working well on my side. I just wanted to ask what the roadmap or plan is for when the "manage" screen might be ready. Is this something being actively worked on? Are we talking probably months or years before this comes to fruition?

Many thanks again.

**Comment by QuintenJustus** [comment]
Hi Robtesch! Thanks! An official roadmap is yet to be made for the public. 

The Management Mode is currently being worked on and will be included in the next release - version 1.2. I estimate that 1.2 will be released within 2 to 3 weeks.

**Comment by robtesch** [comment]
@QuintenJustus Music to my ears! Please do continue the fantastic work.
