### ISSUE TITLE
Support Laravel 6.0

### ISSUE THREAD

**Issue by seedgabo** [Protoqol/Prequel#78]
is any plan to support laravel 6.0 soon?

**Comment by QuintenJustus** [comment]
Will check if support is already there tonight, should be relatively simple, and if that is the case, adding support will simply be changing 1 character in the composer.json 👌

**Comment by QuintenJustus** [comment]
Support is confirmed, you can now use version 1.22.1 with Laravel >6.0

**Comment by seedgabo** [comment]
Perfect 👌, thanks
