### ISSUE TITLE
[FEATURE REQUEST] Authorisation updates (Potential bug?)

### ISSUE THREAD

**Issue by Mikeyspike** [Protoqol/Prequel#84]
**Is your feature request related to a problem? Please describe.**
Seems like Prequel strips out any authorisation when you hit the main page, meaning it's not possible to update / create any middleware which checks agains certain levels of access

This also means it's possible to access prequel without being logged into any area of the application.

**Describe the solution you'd like**
Ability to keep any logged in session in order to be able to check against certain guards or permissions on the logged in user.

**Additional context**
Not sure if this is actually a bug? just seems strange that there's no auth carried over, but if I head back to the rest of my application, I still have a session.

**Comment by ahmad-shawky** [comment]
Also i faced same issue. If i added custom middleware to config to authorize user

**Comment by ahmad-shawky** [comment]
@Mikeyspike You should add 'web' middleware to config file

**Comment by QuintenJustus** [comment]
Hi @Mikeyspike, Prequel on its own provides a very spartan like middleware protection, secure but extremely simple. Like @ahmad-shawky commented, you should probably add your own middleware or the standard 'web' middelware group.
