### ISSUE TITLE
[BUG] Can not install on laravel 6

### ISSUE THREAD

**Issue by sctouch** [Protoqol/Prequel#85]
Problem 1
    - Installation request for composer/composer (locked at 1.9.0) -> satisfiable by composer/composer[1.9.0].
    - protoqol/prequel v1.22 requires composer/composer dev-master -> satisfiable by composer/composer[dev-master].
    - protoqol/prequel v1.22.1 requires composer/composer dev-master -> satisfiable by composer/composer[dev-master].
    - Conclusion: don't install composer/composer dev-master
    - Installation request for protoqol/prequel ^1.22 -> satisfiable by protoqol/prequel[v1.22, v1.22.1].

**Comment by dima2306** [comment]
I have the same problem... Laravel Framework 6.4.1

**Comment by QuintenJustus** [comment]
Should be fixed now :+1:

**Comment by sctouch** [comment]
Thanks you .

**Comment by sctouch** [comment]
I tried but it is not works:

Problem 1
    - Installation request for composer/composer (locked at 1.9.1) -> satisfiable by composer/composer[1.9.1].
    - protoqol/prequel v1.22 requires composer/composer dev-master -> satisfiable by composer/composer[dev-master].
    - protoqol/prequel v1.22.1 requires composer/composer dev-master -> satisfiable by composer/composer[dev-master].
    - Conclusion: don't install composer/composer dev-master
    - Installation request for protoqol/prequel ^1.22 -> satisfiable by protoqol/prequel[v1.22, v1.22.1].

**Comment by QuintenJustus** [comment]
Seems like composer didn't pick up the new release, will fix asap.

**Comment by QuintenJustus** [comment]
Should now be working on Laravel 6
