### ISSUE TITLE
[FEATURE REQUEST] Align table headings and cells left

### ISSUE THREAD

**Issue by roarkmccolgan** [Protoqol/Prequel#86]
**Is your feature request related to a problem? Please describe.**
More of a personal preference but left aligning data tables makes it more readable to me

**Describe the solution you'd like**
Would be great if you could left align table data

**Additional context**
Here is a shot of the demo with centered data:
![image](https://user-images.githubusercontent.com/1567162/67746208-b1cdb980-fa2e-11e9-9e04-8a1adb6a6db1.png)

Here is a shot of the demo with left aligned:
![image](https://user-images.githubusercontent.com/1567162/67746185-a11d4380-fa2e-11e9-8045-5eed946338ed.png)

**Comment by QuintenJustus** [comment]
Thanks for your suggestion! The next release will improve upon UI configuration very much, so be on the lookout to see when your idea has made it into a release 😄
