### ISSUE TITLE
[BUG] /prequel throwing an error - Blank White Page

### ISSUE THREAD

**Issue by milanchheda** [Protoqol/Prequel#89]
**Describe the bug**
After installing the package, I tried to access /prequel and it's showing a blank white page. Error in the console.

**To Reproduce**
1. Install the package as mentioned in the documentation
2. Access /prequel and blank white page

**Expected behavior**
The /prequel page showing the databases and tables.

**Screenshots**
![image](https://user-images.githubusercontent.com/1329515/72332817-26320380-36d4-11ea-9c5d-b0c963aef45d.png)

**PHP Version**
 - Version 7.2

**Database type**
- MySQL

**Desktop (please complete the following information):**
 - Chrome
 - Version 79.0.3945.117

**Comment by QuintenJustus** [comment]
Could you, if you're still using Prequel of course, try again with the latest version? Thanks in advance!

**Comment by milanchheda** [comment]
Hey @QuintenJustus , thanks for fixing. I had used in one of our old projects, don't have access anymore.
