### ISSUE TITLE
Syntax Error when Clicking the Tables

### ISSUE THREAD

**Issue by renztoygwapo** [Protoqol/Prequel#94]
Successfully run the Prequel package by accessing this page /prequel but when I clicked the table menu under the database it will throw a syntax error 
see image below.

![image](https://user-images.githubusercontent.com/4898681/72950459-6aa15b80-3dc6-11ea-889e-47a3b0f121ba.png)

**Comment by QuintenJustus** [comment]
What version of PHP are you running?

**Comment by renztoygwapo** [comment]
PHP 7.2.26 on laravel valet

**Comment by QuintenJustus** [comment]
This should've been fixed in the latest release (v1.22.4).
