### ISSUE TITLE
[BUG] Error after updating

### ISSUE THREAD

**Issue by coding-sunshine** [Protoqol/Prequel#95]
**Describe the bug**
After updating to latest version noticed that it stopped working.
After some debugging found the error at the following place
prequel/src/Http/Controllers/DatabaseController.php
line 90

**To Reproduce**

**Expected behavior**

**Screenshots**

**PHP Version**
 - Version [e.g. 5.6, 7.1]

**Database type**
 - Type [e.g. mysql, pgsql]
 - Version [e.g. v5.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by QuintenJustus** [comment]
This has been fixed in the latest release! Simply update to get rid of the problem.
