### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by krisidmisso** [Protoqol/Prequel#97]
**Is your feature request related to a problem? Please describe.**
Readability and Dark mode are saved on session
**Describe the solution you'd like**
Save readability and Dark mode settings in database or file
**Describe alternatives you've considered**
Add .env variables for global configuration

**Comment by QuintenJustus** [comment]
This is certainly a good suggestion! I think saving it in localStorage will provide the best spot to keep these variables in. Be on the lookout for new releases as this will probably be added very soon 👍
